language: python

cache:
  directories:
    - ~/.cache/pip
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

python:
  - "2.7"
  - "3.6"

services:
  - xvfb

before_script: # configure a headless display to test plot generation
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 6 # give xvfb some time to start

before_install:
  - python -m pip install -U pip
  - python -m pip install -r requirements-dev.txt

install:
  - pip install -e .[test,plot]

script:
  - python -m pytest --cov rio_hist --cov-report term-missing

after_success:
  - coveralls

deploy:
  on:
    tags: true
  provider: pypi
  distribution: "sdist bdist_wheel"
  user: __token__
